//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.UserProfile.Module {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemForm() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.UserProfile.Module.ItemForm", typeof(ItemForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 住　　址 的當地語系化字串。
        /// </summary>
        public static string 住址 {
            get {
                return ResourceManager.GetString("住址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓　　名 的當地語系化字串。
        /// </summary>
        public static string 姓名 {
            get {
                return ResourceManager.GetString("姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密　　碼 的當地語系化字串。
        /// </summary>
        public static string 密碼 {
            get {
                return ResourceManager.GetString("密碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼欄位若保持空白，更新後不修改原密碼。 的當地語系化字串。
        /// </summary>
        public static string 密碼欄位若保持空白更新後不修改原密碼 {
            get {
                return ResourceManager.GetString("密碼欄位若保持空白更新後不修改原密碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳　　號 的當地語系化字串。
        /// </summary>
        public static string 帳號 {
            get {
                return ResourceManager.GetString("帳號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 常用電子郵件 的當地語系化字串。
        /// </summary>
        public static string 常用電子郵件 {
            get {
                return ResourceManager.GetString("常用電子郵件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 平台系統管理員 的當地語系化字串。
        /// </summary>
        public static string 平台系統管理員 {
            get {
                return ResourceManager.GetString("平台系統管理員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會　　員 的當地語系化字串。
        /// </summary>
        public static string 會員 {
            get {
                return ResourceManager.GetString("會員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人 的當地語系化字串。
        /// </summary>
        public static string 營業人 {
            get {
                return ResourceManager.GetString("營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行動電話 的當地語系化字串。
        /// </summary>
        public static string 行動電話 {
            get {
                return ResourceManager.GetString("行動電話", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料稽核員 的當地語系化字串。
        /// </summary>
        public static string 資料稽核員 {
            get {
                return ResourceManager.GetString("資料稽核員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份設定 的當地語系化字串。
        /// </summary>
        public static string 身份設定 {
            get {
                return ResourceManager.GetString("身份設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新輸入密碼 的當地語系化字串。
        /// </summary>
        public static string 重新輸入密碼 {
            get {
                return ResourceManager.GetString("重新輸入密碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 長度最少需要 6 個字元，由英文、數字組成。	 的當地語系化字串。
        /// </summary>
        public static string 長度最少需要_6_個字元由英文數字組成 {
            get {
                return ResourceManager.GetString("長度最少需要 6 個字元由英文數字組成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話（夜） 的當地語系化字串。
        /// </summary>
        public static string 電話_夜 {
            get {
                return ResourceManager.GetString("電話_夜", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話（日） 的當地語系化字串。
        /// </summary>
        public static string 電話_日 {
            get {
                return ResourceManager.GetString("電話_日", resourceCulture);
            }
        }
    }
}
