//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.AllowanceProcess {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AllowanceQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllowanceQuery() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.AllowanceProcess.AllowanceQuery", typeof(AllowanceQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 全部 的當地語系化字串。
        /// </summary>
        public static string 全部 {
            get {
                return ResourceManager.GetString("全部", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印 的當地語系化字串。
        /// </summary>
        public static string 列印 {
            get {
                return ResourceManager.GetString("列印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出 的當地語系化字串。
        /// </summary>
        public static string 匯出 {
            get {
                return ResourceManager.GetString("匯出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單據狀態 的當地語系化字串。
        /// </summary>
        public static string 單據狀態 {
            get {
                return ResourceManager.GetString("單據狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已作廢 的當地語系化字串。
        /// </summary>
        public static string 已作廢 {
            get {
                return ResourceManager.GetString("已作廢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 折讓證明查詢 的當地語系化字串。
        /// </summary>
        public static string 折讓證明查詢 {
            get {
                return ResourceManager.GetString("折讓證明查詢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期區間 的當地語系化字串。
        /// </summary>
        public static string 日期區間 {
            get {
                return ResourceManager.GetString("日期區間", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未作廢 的當地語系化字串。
        /// </summary>
        public static string 未作廢 {
            get {
                return ResourceManager.GetString("未作廢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string 查詢 {
            get {
                return ResourceManager.GetString("查詢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢QR Code證明聯類型 的當地語系化字串。
        /// </summary>
        public static string 查詢QR_Code證明聯類型 {
            get {
                return ResourceManager.GetString("查詢QR Code證明聯類型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢全部 的當地語系化字串。
        /// </summary>
        public static string 查詢全部 {
            get {
                return ResourceManager.GetString("查詢全部", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢條件 的當地語系化字串。
        /// </summary>
        public static string 查詢條件 {
            get {
                return ResourceManager.GetString("查詢條件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢營業人交易類型 的當地語系化字串。
        /// </summary>
        public static string 查詢營業人交易類型 {
            get {
                return ResourceManager.GetString("查詢營業人交易類型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每頁資料筆數 的當地語系化字串。
        /// </summary>
        public static string 每頁資料筆數 {
            get {
                return ResourceManager.GetString("每頁資料筆數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票／折讓單號碼 的當地語系化字串。
        /// </summary>
        public static string 發票_折讓單號碼 {
            get {
                return ResourceManager.GetString("發票_折讓單號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票類別 的當地語系化字串。
        /// </summary>
        public static string 發票類別 {
            get {
                return ResourceManager.GetString("發票類別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自 的當地語系化字串。
        /// </summary>
        public static string 自 {
            get {
                return ResourceManager.GetString("自", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 至 的當地語系化字串。
        /// </summary>
        public static string 至 {
            get {
                return ResourceManager.GetString("至", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇列印資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇列印資料__ {
            get {
                return ResourceManager.GetString("請選擇列印資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇待重送資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇待重送資料__ {
            get {
                return ResourceManager.GetString("請選擇待重送資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人名稱 的當地語系化字串。
        /// </summary>
        public static string 買受人名稱 {
            get {
                return ResourceManager.GetString("買受人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人統編 的當地語系化字串。
        /// </summary>
        public static string 買受人統編 {
            get {
                return ResourceManager.GetString("買受人統編", resourceCulture);
            }
        }
    }
}
