//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.InvoiceNo {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceNoIntervalManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceNoIntervalManager() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.InvoiceNo.InvoiceNoIntervalManager", typeof(InvoiceNoIntervalManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 POS本組數配置 的當地語系化字串。
        /// </summary>
        public static string POS本組數配置 {
            get {
                return ResourceManager.GetString("POS本組數配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全部 的當地語系化字串。
        /// </summary>
        public static string 全部 {
            get {
                return ResourceManager.GetString("全部", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增/修改發票號碼區間 的當地語系化字串。
        /// </summary>
        public static string 新增_修改發票號碼區間 {
            get {
                return ResourceManager.GetString("新增/修改發票號碼區間", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 月 的當地語系化字串。
        /// </summary>
        public static string 月 {
            get {
                return ResourceManager.GetString("月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string 查詢 {
            get {
                return ResourceManager.GetString("查詢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢條件 的當地語系化字串。
        /// </summary>
        public static string 查詢條件 {
            get {
                return ResourceManager.GetString("查詢條件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票年度（民國年） 的當地語系化字串。
        /// </summary>
        public static string 發票年度_民國年_ {
            get {
                return ResourceManager.GetString("發票年度_民國年_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票期別 的當地語系化字串。
        /// </summary>
        public static string 發票期別 {
            get {
                return ResourceManager.GetString("發票期別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定分割此配號區間? 的當地語系化字串。
        /// </summary>
        public static string 確定分割此配號區間_ {
            get {
                return ResourceManager.GetString("確定分割此配號區間?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定刪除此筆資料? 的當地語系化字串。
        /// </summary>
        public static string 確定刪除此筆資料_ {
            get {
                return ResourceManager.GetString("確定刪除此筆資料?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料已刪除!! 的當地語系化字串。
        /// </summary>
        public static string 資料已刪除__ {
            get {
                return ResourceManager.GetString("資料已刪除!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料已更新!! 的當地語系化字串。
        /// </summary>
        public static string 資料已更新__ {
            get {
                return ResourceManager.GetString("資料已更新!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 配號區間已分割!! 的當地語系化字串。
        /// </summary>
        public static string 配號區間已分割__ {
            get {
                return ResourceManager.GetString("配號區間已分割!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立人統編 的當地語系化字串。
        /// </summary>
        public static string 開立人統編 {
            get {
                return ResourceManager.GetString("開立人統編", resourceCulture);
            }
        }
    }
}
