//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.OrganizationQuery.Module {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompanyList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyList() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.OrganizationQuery.Module.CompanyList", typeof(CompanyList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 下載G/W 的當地語系化字串。
        /// </summary>
        public static string 下載G_W {
            get {
                return ResourceManager.GetString("下載G/W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        public static string 停用 {
            get {
                return ResourceManager.GetString("停用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用 的當地語系化字串。
        /// </summary>
        public static string 啟用 {
            get {
                return ResourceManager.GetString("啟用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 店家名稱 的當地語系化字串。
        /// </summary>
        public static string 店家名稱 {
            get {
                return ResourceManager.GetString("店家名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 店家狀態 的當地語系化字串。
        /// </summary>
        public static string 店家狀態 {
            get {
                return ResourceManager.GetString("店家狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增開立人 的當地語系化字串。
        /// </summary>
        public static string 新增開立人 {
            get {
                return ResourceManager.GetString("新增開立人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 用戶端G/W設定 的當地語系化字串。
        /// </summary>
        public static string 用戶端G_W設定 {
            get {
                return ResourceManager.GetString("用戶端G/W設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 社福機構 的當地語系化字串。
        /// </summary>
        public static string 社福機構 {
            get {
                return ResourceManager.GetString("社福機構", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理 的當地語系化字串。
        /// </summary>
        public static string 管理 {
            get {
                return ResourceManager.GetString("管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理使用者 的當地語系化字串。
        /// </summary>
        public static string 管理使用者 {
            get {
                return ResourceManager.GetString("管理使用者", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統一編號 的當地語系化字串。
        /// </summary>
        public static string 統一編號 {
            get {
                return ResourceManager.GetString("統一編號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        public static string 編輯 {
            get {
                return ResourceManager.GetString("編輯", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定POS機號 的當地語系化字串。
        /// </summary>
        public static string 設定POS機號 {
            get {
                return ResourceManager.GetString("設定POS機號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定為B2B營業人 的當地語系化字串。
        /// </summary>
        public static string 設定為B2B營業人 {
            get {
                return ResourceManager.GetString("設定為B2B營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定發票代理店家 的當地語系化字串。
        /// </summary>
        public static string 設定發票代理店家 {
            get {
                return ResourceManager.GetString("設定發票代理店家", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定社福機構 的當地語系化字串。
        /// </summary>
        public static string 設定社福機構 {
            get {
                return ResourceManager.GetString("設定社福機構", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇功能 的當地語系化字串。
        /// </summary>
        public static string 請選擇功能 {
            get {
                return ResourceManager.GetString("請選擇功能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 負責人姓名 的當地語系化字串。
        /// </summary>
        public static string 負責人姓名 {
            get {
                return ResourceManager.GetString("負責人姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件 的當地語系化字串。
        /// </summary>
        public static string 電子郵件 {
            get {
                return ResourceManager.GetString("電子郵件", resourceCulture);
            }
        }
    }
}
