//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.Common {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TreeView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TreeView() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.Common.TreeView", typeof(TreeView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 &gt; 會員管理維護 的當地語系化字串。
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入商務關係相對營業人 的當地語系化字串。
        /// </summary>
        public static string 匯入商務關係相對營業人 {
            get {
                return ResourceManager.GetString("匯入商務關係相對營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相對營業人管理-匯入相對營業人資料 的當地語系化字串。
        /// </summary>
        public static string 相對營業人管理_匯入相對營業人資料 {
            get {
                return ResourceManager.GetString("相對營業人管理_匯入相對營業人資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        public static string 首頁 {
            get {
                return ResourceManager.GetString("首頁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 &gt; 發票作業 的當地語系化字串。
        /// </summary>
        public static string 首頁___發票作業 {
            get {
                return ResourceManager.GetString("首頁 > 發票作業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 &gt; 相對營業人管理 的當地語系化字串。
        /// </summary>
        public static string 首頁___相對營業人管理 {
            get {
                return ResourceManager.GetString("首頁 > 相對營業人管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 &gt; 系統管理維護 的當地語系化字串。
        /// </summary>
        public static string 首頁___系統管理維護 {
            get {
                return ResourceManager.GetString("首頁 > 系統管理維護", resourceCulture);
            }
        }
    }
}
