//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.InvoiceQuery {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceMediaReportCBM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceMediaReportCBM() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.InvoiceQuery.InvoiceMediaReportCBM", typeof(InvoiceMediaReportCBM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 交易筆數 的當地語系化字串。
        /// </summary>
        public static string 交易筆數 {
            get {
                return ResourceManager.GetString("交易筆數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯率 的當地語系化字串。
        /// </summary>
        public static string 匯率 {
            get {
                return ResourceManager.GetString("匯率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 幣別 的當地語系化字串。
        /// </summary>
        public static string 幣別 {
            get {
                return ResourceManager.GetString("幣別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 換算後銷售總計金額 的當地語系化字串。
        /// </summary>
        public static string 換算後銷售總計金額 {
            get {
                return ResourceManager.GetString("換算後銷售總計金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 格式代號 的當地語系化字串。
        /// </summary>
        public static string 格式代號 {
            get {
                return ResourceManager.GetString("格式代號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票起號 的當地語系化字串。
        /// </summary>
        public static string 發票起號 {
            get {
                return ResourceManager.GetString("發票起號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票迄號 的當地語系化字串。
        /// </summary>
        public static string 發票迄號 {
            get {
                return ResourceManager.GetString("發票迄號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統一發票字軌 的當地語系化字串。
        /// </summary>
        public static string 統一發票字軌 {
            get {
                return ResourceManager.GetString("統一發票字軌", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料所屬期別(年月) 的當地語系化字串。
        /// </summary>
        public static string 資料所屬期別_年月_ {
            get {
                return ResourceManager.GetString("資料所屬期別(年月)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售總計金額 的當地語系化字串。
        /// </summary>
        public static string 銷售總計金額 {
            get {
                return ResourceManager.GetString("銷售總計金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售額 的當地語系化字串。
        /// </summary>
        public static string 銷售額 {
            get {
                return ResourceManager.GetString("銷售額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷項稅額 的當地語系化字串。
        /// </summary>
        public static string 銷項稅額 {
            get {
                return ResourceManager.GetString("銷項稅額", resourceCulture);
            }
        }
    }
}
