//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.BusinessRelationship.Module {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImportCounterpartBusinessBranch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportCounterpartBusinessBranch() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.BusinessRelationship.Module.ImportCounterpartBusinessBranch" +
                            "", typeof(ImportCounterpartBusinessBranch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 上頁 的當地語系化字串。
        /// </summary>
        public static string 上頁 {
            get {
                return ResourceManager.GetString("上頁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下頁 的當地語系化字串。
        /// </summary>
        public static string 下頁 {
            get {
                return ResourceManager.GetString("下頁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入分店相對營業人資料 的當地語系化字串。
        /// </summary>
        public static string 匯入分店相對營業人資料 {
            get {
                return ResourceManager.GetString("匯入分店相對營業人資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入檔案範本 的當地語系化字串。
        /// </summary>
        public static string 匯入檔案範本 {
            get {
                return ResourceManager.GetString("匯入檔案範本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入資料完成!! 的當地語系化字串。
        /// </summary>
        public static string 匯入資料完成__ {
            get {
                return ResourceManager.GetString("匯入資料完成!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所屬集團成員 的當地語系化字串。
        /// </summary>
        public static string 所屬集團成員 {
            get {
                return ResourceManager.GetString("所屬集團成員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件編碼 的當地語系化字串。
        /// </summary>
        public static string 文件編碼 {
            get {
                return ResourceManager.GetString("文件編碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最前 的當地語系化字串。
        /// </summary>
        public static string 最前 {
            get {
                return ResourceManager.GetString("最前", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後 的當地語系化字串。
        /// </summary>
        public static string 最後 {
            get {
                return ResourceManager.GetString("最後", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相對營業人資料匯入 的當地語系化字串。
        /// </summary>
        public static string 相對營業人資料匯入 {
            get {
                return ResourceManager.GetString("相對營業人資料匯入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相對營業人類別 的當地語系化字串。
        /// </summary>
        public static string 相對營業人類別 {
            get {
                return ResourceManager.GetString("相對營業人類別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        public static string 確定 {
            get {
                return ResourceManager.GetString("確定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認 的當地語系化字串。
        /// </summary>
        public static string 確認 {
            get {
                return ResourceManager.GetString("確認", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繁體中文 的當地語系化字串。
        /// </summary>
        public static string 繁體中文 {
            get {
                return ResourceManager.GetString("繁體中文", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請依據檔案中各欄位名稱填入相對應內容，每一列代表唯一家相對營業人資料，若匯入資料已存在系統，系統會以編輯方式修改原存在資料 的當地語系化字串。
        /// </summary>
        public static string 請依據檔案中各欄位名稱填入相對應內容_每一列代表唯一家相對營業人資料_若匯入資料已存在系統_系統會以編輯方式修改原存在資料 {
            get {
                return ResourceManager.GetString("請依據檔案中各欄位名稱填入相對應內容_每一列代表唯一家相對營業人資料_若匯入資料已存在系統_系統會以編輯方式修改原存在資料", resourceCulture);
            }
        }
    }
}
