//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.BusinessRelationship.Module {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaintainBusinessRelationship {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintainBusinessRelationship() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.BusinessRelationship.Module.MaintainBusinessRelationship", typeof(MaintainBusinessRelationship).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 主動列印 的當地語系化字串。
        /// </summary>
        public static string 主動列印 {
            get {
                return ResourceManager.GetString("主動列印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者管理 的當地語系化字串。
        /// </summary>
        public static string 使用者管理 {
            get {
                return ResourceManager.GetString("使用者管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全部 的當地語系化字串。
        /// </summary>
        public static string 全部 {
            get {
                return ResourceManager.GetString("全部", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入分店相對營業人 的當地語系化字串。
        /// </summary>
        public static string 匯入分店相對營業人 {
            get {
                return ResourceManager.GetString("匯入分店相對營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入商務關係相對營業人 的當地語系化字串。
        /// </summary>
        public static string 匯入商務關係相對營業人 {
            get {
                return ResourceManager.GetString("匯入商務關係相對營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入相對營業人 的當地語系化字串。
        /// </summary>
        public static string 匯入相對營業人 {
            get {
                return ResourceManager.GetString("匯入相對營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已停用 的當地語系化字串。
        /// </summary>
        public static string 已停用 {
            get {
                return ResourceManager.GetString("已停用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已啟用 的當地語系化字串。
        /// </summary>
        public static string 已啟用 {
            get {
                return ResourceManager.GetString("已啟用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 店號 的當地語系化字串。
        /// </summary>
        public static string 店號 {
            get {
                return ResourceManager.GetString("店號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string 查詢 {
            get {
                return ResourceManager.GetString("查詢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢條件 的當地語系化字串。
        /// </summary>
        public static string 查詢條件 {
            get {
                return ResourceManager.GetString("查詢條件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人名稱 的當地語系化字串。
        /// </summary>
        public static string 營業人名稱 {
            get {
                return ResourceManager.GetString("營業人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人狀態 的當地語系化字串。
        /// </summary>
        public static string 營業人狀態 {
            get {
                return ResourceManager.GetString("營業人狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人統編 的當地語系化字串。
        /// </summary>
        public static string 營業人統編 {
            get {
                return ResourceManager.GetString("營業人統編", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人類別 的當地語系化字串。
        /// </summary>
        public static string 營業人類別 {
            get {
                return ResourceManager.GetString("營業人類別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相對營業人資料維護 的當地語系化字串。
        /// </summary>
        public static string 相對營業人資料維護 {
            get {
                return ResourceManager.GetString("相對營業人資料維護", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認停用列印? 的當地語系化字串。
        /// </summary>
        public static string 確認停用列印_ {
            get {
                return ResourceManager.GetString("確認停用列印?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認停用此營業人? 的當地語系化字串。
        /// </summary>
        public static string 確認停用此營業人_ {
            get {
                return ResourceManager.GetString("確認停用此營業人?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認刪除此營業人關係? 的當地語系化字串。
        /// </summary>
        public static string 確認刪除此營業人關係_ {
            get {
                return ResourceManager.GetString("確認刪除此營業人關係?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認啟用此營業人? 的當地語系化字串。
        /// </summary>
        public static string 確認啟用此營業人_ {
            get {
                return ResourceManager.GetString("確認啟用此營業人?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認啟用此營業人自動接收? 的當地語系化字串。
        /// </summary>
        public static string 確認啟用此營業人自動接收_ {
            get {
                return ResourceManager.GetString("確認啟用此營業人自動接收?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自動接收 的當地語系化字串。
        /// </summary>
        public static string 自動接收 {
            get {
                return ResourceManager.GetString("自動接收", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料已刪除!! 的當地語系化字串。
        /// </summary>
        public static string 資料已刪除__ {
            get {
                return ResourceManager.GetString("資料已刪除!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料已更新!! 的當地語系化字串。
        /// </summary>
        public static string 資料已更新__ {
            get {
                return ResourceManager.GetString("資料已更新!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 集團成員 的當地語系化字串。
        /// </summary>
        public static string 集團成員 {
            get {
                return ResourceManager.GetString("集團成員", resourceCulture);
            }
        }
    }
}
