//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.ModelExtension.DataExchange {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrackCodeExchange {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrackCodeExchange() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.ModelExtension.DataExchange.TrackCodeExchange", typeof(TrackCodeExchange).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 只接受發票類別07、08 的當地語系化字串。
        /// </summary>
        public static string 只接受發票類別07_08 {
            get {
                return ResourceManager.GetString("只接受發票類別07_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 字軌 的當地語系化字串。
        /// </summary>
        public static string 字軌 {
            get {
                return ResourceManager.GetString("字軌", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 字軌已存在 的當地語系化字串。
        /// </summary>
        public static string 字軌已存在 {
            get {
                return ResourceManager.GetString("字軌已存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 字軌已新增 的當地語系化字串。
        /// </summary>
        public static string 字軌已新增 {
            get {
                return ResourceManager.GetString("字軌已新增", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 字軌格式錯誤 的當地語系化字串。
        /// </summary>
        public static string 字軌格式錯誤 {
            get {
                return ResourceManager.GetString("字軌格式錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 字軌種類 的當地語系化字串。
        /// </summary>
        public static string 字軌種類 {
            get {
                return ResourceManager.GetString("字軌種類", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 字軌錯誤 的當地語系化字串。
        /// </summary>
        public static string 字軌錯誤 {
            get {
                return ResourceManager.GetString("字軌錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 期別 的當地語系化字串。
        /// </summary>
        public static string 期別 {
            get {
                return ResourceManager.GetString("期別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 期別格式錯誤 的當地語系化字串。
        /// </summary>
        public static string 期別格式錯誤 {
            get {
                return ResourceManager.GetString("期別格式錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未設定期別 的當地語系化字串。
        /// </summary>
        public static string 未設定期別 {
            get {
                return ResourceManager.GetString("未設定期別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票字軌 的當地語系化字串。
        /// </summary>
        public static string 發票字軌 {
            get {
                return ResourceManager.GetString("發票字軌", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票類別 的當地語系化字串。
        /// </summary>
        public static string 發票類別 {
            get {
                return ResourceManager.GetString("發票類別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理狀態 的當地語系化字串。
        /// </summary>
        public static string 處理狀態 {
            get {
                return ResourceManager.GetString("處理狀態", resourceCulture);
            }
        }
    }
}
