//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.8.3928.0 自動產生。
// 
namespace InvoiceClient.Agent.TurnkeyProcess {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SummaryResult {
        
        /// <remarks/>
        public SummaryResultRoutingInfo RoutingInfo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public SummaryResultMessage[] DetailList;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultRoutingInfo {
        
        /// <remarks/>
        public SummaryResultRoutingInfoFrom From;
        
        /// <remarks/>
        public SummaryResultRoutingInfoFromVAC FromVAC;
        
        /// <remarks/>
        public SummaryResultRoutingInfoTO To;
        
        /// <remarks/>
        public SummaryResultRoutingInfoToVAC ToVAC;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultRoutingInfoFrom {
        
        /// <remarks/>
        public uint PartyId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultRoutingInfoFromVAC {
        
        /// <remarks/>
        public string RoutingId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultRoutingInfoTO {
        
        /// <remarks/>
        public uint PartyId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultRoutingInfoToVAC {
        
        /// <remarks/>
        public uint RoutingId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessage {
        
        /// <remarks/>
        public SummaryResultMessageInfo Info;
        
        /// <remarks/>
        public SummaryResultMessageResultType ResultType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageInfo {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public uint Size;
        
        /// <remarks/>
        public string MessageType;
        
        /// <remarks/>
        public string Service;
        
        /// <remarks/>
        public string Action;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultType {
        
        /// <remarks/>
        public SummaryResultMessageResultTypeTotal Total;
        
        /// <remarks/>
        public SummaryResultMessageResultTypeGood Good;
        
        /// <remarks/>
        public SummaryResultMessageResultTypeFailed Failed;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultTypeTotal {
        
        /// <remarks/>
        public SummaryResultMessageResultTypeTotalResultDetailType ResultDetailType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultTypeTotalResultDetailType {
        
        /// <remarks/>
        public uint Count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Invoice", IsNullable=false)]
        public SummaryResultMessageResultTypeTotalResultDetailTypeInvoice[] Invoices;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultTypeTotalResultDetailTypeInvoice {
        
        /// <remarks/>
        public string ReferenceNumber;
        
        /// <remarks/>
        public uint InvoiceDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultTypeGood {
        
        /// <remarks/>
        public SummaryResultMessageResultTypeGoodResultDetailType ResultDetailType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultTypeGoodResultDetailType {
        
        /// <remarks/>
        public uint Count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Invoice", IsNullable=false)]
        public SummaryResultMessageResultTypeGoodResultDetailTypeInvoice[] Invoices;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultTypeGoodResultDetailTypeInvoice {
        
        /// <remarks/>
        public string ReferenceNumber;
        
        /// <remarks/>
        public uint InvoiceDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultTypeFailed {
        
        /// <remarks/>
        public SummaryResultMessageResultTypeFailedResultDetailType ResultDetailType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultTypeFailedResultDetailType {
        
        /// <remarks/>
        public uint Count;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Invoice", IsNullable=false)]
        public SummaryResultMessageResultTypeFailedResultDetailTypeInvoice[] Invoices;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SummaryResultMessageResultTypeFailedResultDetailTypeInvoice {
        
        /// <remarks/>
        public string ReferenceNumber;
        
        /// <remarks/>
        public uint InvoiceDate;
    }
}
