//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.InquireInvoice {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ByCarrierType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ByCarrierType() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.InquireInvoice.ByCarrierType", typeof(ByCarrierType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 一卡通 的當地語系化字串。
        /// </summary>
        public static string 一卡通 {
            get {
                return ResourceManager.GetString("一卡通", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 信用卡 的當地語系化字串。
        /// </summary>
        public static string 信用卡 {
            get {
                return ResourceManager.GetString("信用卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全部 的當地語系化字串。
        /// </summary>
        public static string 全部 {
            get {
                return ResourceManager.GetString("全部", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 台灣智慧卡 的當地語系化字串。
        /// </summary>
        public static string 台灣智慧卡 {
            get {
                return ResourceManager.GetString("台灣智慧卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 悠遊卡 的當地語系化字串。
        /// </summary>
        public static string 悠遊卡 {
            get {
                return ResourceManager.GetString("悠遊卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手機條碼 的當地語系化字串。
        /// </summary>
        public static string 手機條碼 {
            get {
                return ResourceManager.GetString("手機條碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網際優勢會員條碼 的當地語系化字串。
        /// </summary>
        public static string 網際優勢會員條碼 {
            get {
                return ResourceManager.GetString("網際優勢會員條碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自然人憑證條碼 的當地語系化字串。
        /// </summary>
        public static string 自然人憑證條碼 {
            get {
                return ResourceManager.GetString("自然人憑證條碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行動 X 卡 的當地語系化字串。
        /// </summary>
        public static string 行動_X_卡 {
            get {
                return ResourceManager.GetString("行動 X 卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載具類型 的當地語系化字串。
        /// </summary>
        public static string 載具類型 {
            get {
                return ResourceManager.GetString("載具類型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金融卡 的當地語系化字串。
        /// </summary>
        public static string 金融卡 {
            get {
                return ResourceManager.GetString("金融卡", resourceCulture);
            }
        }
    }
}
