//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Helpers {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExtensionMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtensionMethods() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Helpers.ExtensionMethods", typeof(ExtensionMethods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 不提供自行列印，如有需要紙本請與管理部承辦人員連絡，謝謝配合。 的當地語系化字串。
        /// </summary>
        public static string 不提供自行列印_如有需要紙本請與管理部承辦人員連絡_謝謝配合_ {
            get {
                return ResourceManager.GetString("不提供自行列印_如有需要紙本請與管理部承辦人員連絡_謝謝配合_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人發票 的當地語系化字串。
        /// </summary>
        public static string 個人發票 {
            get {
                return ResourceManager.GetString("個人發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品項過長，詳列於發票明細 的當地語系化字串。
        /// </summary>
        public static string 品項過長_詳列於發票明細 {
            get {
                return ResourceManager.GetString("品項過長_詳列於發票明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生發票QR Code失敗 的當地語系化字串。
        /// </summary>
        public static string 產生發票QR_Code失敗 {
            get {
                return ResourceManager.GetString("產生發票QR Code失敗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票已列印 的當地語系化字串。
        /// </summary>
        public static string 發票已列印 {
            get {
                return ResourceManager.GetString("發票已列印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請取得授權列印!! 的當地語系化字串。
        /// </summary>
        public static string 請取得授權列印__ {
            get {
                return ResourceManager.GetString("請取得授權列印!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入公司名稱!! 的當地語系化字串。
        /// </summary>
        public static string 請輸入公司名稱__ {
            get {
                return ResourceManager.GetString("請輸入公司名稱!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入公司地址!! 的當地語系化字串。
        /// </summary>
        public static string 請輸入公司地址__ {
            get {
                return ResourceManager.GetString("請輸入公司地址!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入公司統編!! 的當地語系化字串。
        /// </summary>
        public static string 請輸入公司統編__ {
            get {
                return ResourceManager.GetString("請輸入公司統編!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入公司電話!! 的當地語系化字串。
        /// </summary>
        public static string 請輸入公司電話__ {
            get {
                return ResourceManager.GetString("請輸入公司電話!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子信箱尚未輸入或輸入錯誤!! 的當地語系化字串。
        /// </summary>
        public static string 電子信箱尚未輸入或輸入錯誤__ {
            get {
                return ResourceManager.GetString("電子信箱尚未輸入或輸入錯誤!!", resourceCulture);
            }
        }
    }
}
