//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.DataView.Module {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Invoice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invoice() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.DataView.Module.Invoice", typeof(Invoice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string 備註 {
            get {
                return ResourceManager.GetString("備註", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 含稅金額 的當地語系化字串。
        /// </summary>
        public static string 含稅金額 {
            get {
                return ResourceManager.GetString("含稅金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品名 的當地語系化字串。
        /// </summary>
        public static string 品名 {
            get {
                return ResourceManager.GetString("品名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單價 的當地語系化字串。
        /// </summary>
        public static string 單價 {
            get {
                return ResourceManager.GetString("單價", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地 址 的當地語系化字串。
        /// </summary>
        public static string 地_址 {
            get {
                return ResourceManager.GetString("地 址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶編號 的當地語系化字串。
        /// </summary>
        public static string 客戶編號 {
            get {
                return ResourceManager.GetString("客戶編號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數量 的當地語系化字串。
        /// </summary>
        public static string 數量 {
            get {
                return ResourceManager.GetString("數量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未稅金額 的當地語系化字串。
        /// </summary>
        public static string 未稅金額 {
            get {
                return ResourceManager.GetString("未稅金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查號碼 的當地語系化字串。
        /// </summary>
        public static string 檢查號碼 {
            get {
                return ResourceManager.GetString("檢查號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票日期 的當地語系化字串。
        /// </summary>
        public static string 發票日期 {
            get {
                return ResourceManager.GetString("發票日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票號碼 的當地語系化字串。
        /// </summary>
        public static string 發票號碼 {
            get {
                return ResourceManager.GetString("發票號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 稅 額 的當地語系化字串。
        /// </summary>
        public static string 稅_額 {
            get {
                return ResourceManager.GetString("稅 額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買方名稱 的當地語系化字串。
        /// </summary>
        public static string 買方名稱 {
            get {
                return ResourceManager.GetString("買方名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買方統一編號 的當地語系化字串。
        /// </summary>
        public static string 買方統一編號 {
            get {
                return ResourceManager.GetString("買方統一編號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金額 的當地語系化字串。
        /// </summary>
        public static string 金額 {
            get {
                return ResourceManager.GetString("金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立人名稱 的當地語系化字串。
        /// </summary>
        public static string 開立人名稱 {
            get {
                return ResourceManager.GetString("開立人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立人統一編號 的當地語系化字串。
        /// </summary>
        public static string 開立人統一編號 {
            get {
                return ResourceManager.GetString("開立人統一編號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隨機碼 的當地語系化字串。
        /// </summary>
        public static string 隨機碼 {
            get {
                return ResourceManager.GetString("隨機碼", resourceCulture);
            }
        }
    }
}
