//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.InvoiceProcess.Module {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditInvoiceBuyer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditInvoiceBuyer() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.InvoiceProcess.Module.EditInvoiceBuyer", typeof(EditInvoiceBuyer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 作業完成!! 的當地語系化字串。
        /// </summary>
        public static string 作業完成__ {
            get {
                return ResourceManager.GetString("作業完成!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票號碼 的當地語系化字串。
        /// </summary>
        public static string 發票號碼 {
            get {
                return ResourceManager.GetString("發票號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        public static string 確定 {
            get {
                return ResourceManager.GetString("確定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯買受人資料 的當地語系化字串。
        /// </summary>
        public static string 編輯買受人資料 {
            get {
                return ResourceManager.GetString("編輯買受人資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人名稱 的當地語系化字串。
        /// </summary>
        public static string 買受人名稱 {
            get {
                return ResourceManager.GetString("買受人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人統編 的當地語系化字串。
        /// </summary>
        public static string 買受人統編 {
            get {
                return ResourceManager.GetString("買受人統編", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連絡人名稱 的當地語系化字串。
        /// </summary>
        public static string 連絡人名稱 {
            get {
                return ResourceManager.GetString("連絡人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連絡人地址 的當地語系化字串。
        /// </summary>
        public static string 連絡人地址 {
            get {
                return ResourceManager.GetString("連絡人地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連絡人電話 的當地語系化字串。
        /// </summary>
        public static string 連絡人電話 {
            get {
                return ResourceManager.GetString("連絡人電話", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵遞區號 的當地語系化字串。
        /// </summary>
        public static string 郵遞區號 {
            get {
                return ResourceManager.GetString("郵遞區號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關閉 的當地語系化字串。
        /// </summary>
        public static string 關閉 {
            get {
                return ResourceManager.GetString("關閉", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顧客ID 的當地語系化字串。
        /// </summary>
        public static string 顧客ID {
            get {
                return ResourceManager.GetString("顧客ID", resourceCulture);
            }
        }
    }
}
