//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Controllers {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AllowanceProcess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllowanceProcess() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Controllers.AllowanceProcess", typeof(AllowanceProcess).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Email通知已重送!! 的當地語系化字串。
        /// </summary>
        public static string Email通知已重送__ {
            get {
                return ResourceManager.GetString("Email通知已重送!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下列折讓已作廢完成!! 的當地語系化字串。
        /// </summary>
        public static string 下列折讓已作廢完成__ {
            get {
                return ResourceManager.GetString("下列折讓已作廢完成!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 作廢折讓 的當地語系化字串。
        /// </summary>
        public static string 作廢折讓 {
            get {
                return ResourceManager.GetString("作廢折讓", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string 備註 {
            get {
                return ResourceManager.GetString("備註", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原發票號碼 的當地語系化字串。
        /// </summary>
        public static string 原發票號碼 {
            get {
                return ResourceManager.GetString("原發票號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 含稅金額 的當地語系化字串。
        /// </summary>
        public static string 含稅金額 {
            get {
                return ResourceManager.GetString("含稅金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶ID 的當地語系化字串。
        /// </summary>
        public static string 客戶ID {
            get {
                return ResourceManager.GetString("客戶ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 折讓單號碼 的當地語系化字串。
        /// </summary>
        public static string 折讓單號碼 {
            get {
                return ResourceManager.GetString("折讓單號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 折讓日期 的當地語系化字串。
        /// </summary>
        public static string 折讓日期 {
            get {
                return ResourceManager.GetString("折讓日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 折讓資料明細 的當地語系化字串。
        /// </summary>
        public static string 折讓資料明細 {
            get {
                return ResourceManager.GetString("折讓資料明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未稅金額 的當地語系化字串。
        /// </summary>
        public static string 未稅金額 {
            get {
                return ResourceManager.GetString("未稅金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票開立人 的當地語系化字串。
        /// </summary>
        public static string 發票開立人 {
            get {
                return ResourceManager.GetString("發票開立人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 稅額 的當地語系化字串。
        /// </summary>
        public static string 稅額 {
            get {
                return ResourceManager.GetString("稅額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇作廢資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇作廢資料__ {
            get {
                return ResourceManager.GetString("請選擇作廢資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇重送資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇重送資料__ {
            get {
                return ResourceManager.GetString("請選擇重送資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人EMail 的當地語系化字串。
        /// </summary>
        public static string 買受人EMail {
            get {
                return ResourceManager.GetString("買受人EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人名稱 的當地語系化字串。
        /// </summary>
        public static string 買受人名稱 {
            get {
                return ResourceManager.GetString("買受人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人統編 的當地語系化字串。
        /// </summary>
        public static string 買受人統編 {
            get {
                return ResourceManager.GetString("買受人統編", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料已列印請重新選擇!! 的當地語系化字串。
        /// </summary>
        public static string 資料已列印請重新選擇__ {
            get {
                return ResourceManager.GetString("資料已列印請重新選擇!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連絡人名稱 的當地語系化字串。
        /// </summary>
        public static string 連絡人名稱 {
            get {
                return ResourceManager.GetString("連絡人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連絡人地址 的當地語系化字串。
        /// </summary>
        public static string 連絡人地址 {
            get {
                return ResourceManager.GetString("連絡人地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立人統編 的當地語系化字串。
        /// </summary>
        public static string 開立人統編 {
            get {
                return ResourceManager.GetString("開立人統編", resourceCulture);
            }
        }
    }
}
