//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Controllers {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Handling {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Handling() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Controllers.Handling", typeof(Handling).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 作業方式 的當地語系化字串。
        /// </summary>
        public static string 作業方式 {
            get {
                return ResourceManager.GetString("作業方式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者非系統管理公司!! 的當地語系化字串。
        /// </summary>
        public static string 使用者非系統管理公司 {
            get {
                return ResourceManager.GetString("使用者非系統管理公司", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備考 的當地語系化字串。
        /// </summary>
        public static string 備考 {
            get {
                return ResourceManager.GetString("備考", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        public static string 姓名 {
            get {
                return ResourceManager.GetString("姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄件地名或地址 的當地語系化字串。
        /// </summary>
        public static string 寄件地名或地址 {
            get {
                return ResourceManager.GetString("寄件地名或地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 掛號號碼 的當地語系化字串。
        /// </summary>
        public static string 掛號號碼 {
            get {
                return ResourceManager.GetString("掛號號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 掛號郵件號碼明細 的當地語系化字串。
        /// </summary>
        public static string 掛號郵件號碼明細 {
            get {
                return ResourceManager.GetString("掛號郵件號碼明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票日期 的當地語系化字串。
        /// </summary>
        public static string 發票日期 {
            get {
                return ResourceManager.GetString("發票日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票號碼 的當地語系化字串。
        /// </summary>
        public static string 發票號碼 {
            get {
                return ResourceManager.GetString("發票號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票資料錯誤!! 的當地語系化字串。
        /// </summary>
        public static string 發票資料錯誤 {
            get {
                return ResourceManager.GetString("發票資料錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票起號由2碼英文+8碼數字組成，共10碼。 的當地語系化字串。
        /// </summary>
        public static string 發票起號由2碼英文_8碼數字組成 {
            get {
                return ResourceManager.GetString("發票起號由2碼英文+8碼數字組成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票起、迄號字軌不相同!! 的當地語系化字串。
        /// </summary>
        public static string 發票起迄號字軌不相同 {
            get {
                return ResourceManager.GetString("發票起迄號字軌不相同", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票迄號由2碼英文+8碼數字組成，共10碼。 的當地語系化字串。
        /// </summary>
        public static string 發票迄號由2碼英文_8碼數字組成 {
            get {
                return ResourceManager.GetString("發票迄號由2碼英文+8碼數字組成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定完成!! 的當地語系化字串。
        /// </summary>
        public static string 設定完成 {
            get {
                return ResourceManager.GetString("設定完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該開立人已是B2B營業人!! 的當地語系化字串。
        /// </summary>
        public static string 該開立人已是B2B營業人 {
            get {
                return ResourceManager.GetString("該開立人已是B2B營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇郵寄過程!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇郵寄過程 {
            get {
                return ResourceManager.GetString("請選擇郵寄過程", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇郵寄項目!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇郵寄項目 {
            get {
                return ResourceManager.GetString("請選擇郵寄項目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料不存在!! 的當地語系化字串。
        /// </summary>
        public static string 資料不存在 {
            get {
                return ResourceManager.GetString("資料不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料已更新!! 的當地語系化字串。
        /// </summary>
        public static string 資料已更新 {
            get {
                return ResourceManager.GetString("資料已更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料錯誤!! 的當地語系化字串。
        /// </summary>
        public static string 資料錯誤 {
            get {
                return ResourceManager.GetString("資料錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遞件日期 的當地語系化字串。
        /// </summary>
        public static string 遞件日期 {
            get {
                return ResourceManager.GetString("遞件日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附件檔頁數 的當地語系化字串。
        /// </summary>
        public static string 附件檔頁數 {
            get {
                return ResourceManager.GetString("附件檔頁數", resourceCulture);
            }
        }
    }
}
