//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Controllers {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceProcess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceProcess() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Controllers.InvoiceProcess", typeof(InvoiceProcess).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Email通知已重送!! 的當地語系化字串。
        /// </summary>
        public static string Email通知已重送__ {
            get {
                return ResourceManager.GetString("Email通知已重送!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QRCode金鑰檔無內容，無法列印!! 的當地語系化字串。
        /// </summary>
        public static string QRCode金鑰檔無內容_無法列印__ {
            get {
                return ResourceManager.GetString("QRCode金鑰檔無內容_無法列印!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下列發票已作廢完成!! 的當地語系化字串。
        /// </summary>
        public static string 下列發票已作廢完成__ {
            get {
                return ResourceManager.GetString("下列發票已作廢完成!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下列發票已核准重印!! 的當地語系化字串。
        /// </summary>
        public static string 下列發票已核准重印__ {
            get {
                return ResourceManager.GetString("下列發票已核准重印!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載資料請求已送出!! 的當地語系化字串。
        /// </summary>
        public static string 下載資料請求已送出__ {
            get {
                return ResourceManager.GetString("下載資料請求已送出!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 作廢電子發票 的當地語系化字串。
        /// </summary>
        public static string 作廢電子發票 {
            get {
                return ResourceManager.GetString("作廢電子發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string 備註 {
            get {
                return ResourceManager.GetString("備註", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 含稅金額 的當地語系化字串。
        /// </summary>
        public static string 含稅金額 {
            get {
                return ResourceManager.GetString("含稅金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地址 的當地語系化字串。
        /// </summary>
        public static string 地址 {
            get {
                return ResourceManager.GetString("地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶ID 的當地語系化字串。
        /// </summary>
        public static string 客戶ID {
            get {
                return ResourceManager.GetString("客戶ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號 的當地語系化字串。
        /// </summary>
        public static string 序號 {
            get {
                return ResourceManager.GetString("序號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 愛心碼 的當地語系化字串。
        /// </summary>
        public static string 愛心碼 {
            get {
                return ResourceManager.GetString("愛心碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收件人姓名 的當地語系化字串。
        /// </summary>
        public static string 收件人姓名 {
            get {
                return ResourceManager.GetString("收件人姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否中獎 的當地語系化字串。
        /// </summary>
        public static string 是否中獎 {
            get {
                return ResourceManager.GetString("是否中獎", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未稅金額 的當地語系化字串。
        /// </summary>
        public static string 未稅金額 {
            get {
                return ResourceManager.GetString("未稅金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 核准註銷發票 的當地語系化字串。
        /// </summary>
        public static string 核准註銷發票 {
            get {
                return ResourceManager.GetString("核准註銷發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 核准重印發票 的當地語系化字串。
        /// </summary>
        public static string 核准重印發票 {
            get {
                return ResourceManager.GetString("核准重印發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無QRCode金鑰檔，無法列印!! 的當地語系化字串。
        /// </summary>
        public static string 無QRCode金鑰檔_無法列印__ {
            get {
                return ResourceManager.GetString("無QRCode金鑰檔_無法列印!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人名稱 的當地語系化字串。
        /// </summary>
        public static string 營業人名稱 {
            get {
                return ResourceManager.GetString("營業人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票列印 的當地語系化字串。
        /// </summary>
        public static string 發票列印 {
            get {
                return ResourceManager.GetString("發票列印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票日期 的當地語系化字串。
        /// </summary>
        public static string 發票日期 {
            get {
                return ResourceManager.GetString("發票日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票處理作業 的當地語系化字串。
        /// </summary>
        public static string 發票處理作業 {
            get {
                return ResourceManager.GetString("發票處理作業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票號碼 的當地語系化字串。
        /// </summary>
        public static string 發票號碼 {
            get {
                return ResourceManager.GetString("發票號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票買受人資料 的當地語系化字串。
        /// </summary>
        public static string 發票買受人資料 {
            get {
                return ResourceManager.GetString("發票買受人資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票資料明細 的當地語系化字串。
        /// </summary>
        public static string 發票資料明細 {
            get {
                return ResourceManager.GetString("發票資料明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票開立人 的當地語系化字串。
        /// </summary>
        public static string 發票開立人 {
            get {
                return ResourceManager.GetString("發票開立人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 稅額 的當地語系化字串。
        /// </summary>
        public static string 稅額 {
            get {
                return ResourceManager.GetString("稅額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註銷發票 的當地語系化字串。
        /// </summary>
        public static string 註銷發票 {
            get {
                return ResourceManager.GetString("註銷發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇下載資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇下載資料__ {
            get {
                return ResourceManager.GetString("請選擇下載資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇作廢資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇作廢資料__ {
            get {
                return ResourceManager.GetString("請選擇作廢資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇核准註銷資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇核准註銷資料__ {
            get {
                return ResourceManager.GetString("請選擇核准註銷資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇核准重印資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇核准重印資料__ {
            get {
                return ResourceManager.GetString("請選擇核准重印資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇發票資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇發票資料__ {
            get {
                return ResourceManager.GetString("請選擇發票資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇相同買受人之發票資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇相同買受人之發票資料__ {
            get {
                return ResourceManager.GetString("請選擇相同買受人之發票資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇相同類型之發票資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇相同類型之發票資料__ {
            get {
                return ResourceManager.GetString("請選擇相同類型之發票資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇註銷資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇註銷資料__ {
            get {
                return ResourceManager.GetString("請選擇註銷資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇重送資料!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇重送資料__ {
            get {
                return ResourceManager.GetString("請選擇重送資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人 的當地語系化字串。
        /// </summary>
        public static string 買受人 {
            get {
                return ResourceManager.GetString("買受人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人EMail 的當地語系化字串。
        /// </summary>
        public static string 買受人EMail {
            get {
                return ResourceManager.GetString("買受人EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人名稱 的當地語系化字串。
        /// </summary>
        public static string 買受人名稱 {
            get {
                return ResourceManager.GetString("買受人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人統編 的當地語系化字串。
        /// </summary>
        public static string 買受人統編 {
            get {
                return ResourceManager.GetString("買受人統編", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人資料錯誤!! 的當地語系化字串。
        /// </summary>
        public static string 買受人資料錯誤__ {
            get {
                return ResourceManager.GetString("買受人資料錯誤!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料錯誤!! 的當地語系化字串。
        /// </summary>
        public static string 資料錯誤__ {
            get {
                return ResourceManager.GetString("資料錯誤!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載具號碼 的當地語系化字串。
        /// </summary>
        public static string 載具號碼 {
            get {
                return ResourceManager.GetString("載具號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載具類別 的當地語系化字串。
        /// </summary>
        public static string 載具類別 {
            get {
                return ResourceManager.GetString("載具類別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連絡人名稱 的當地語系化字串。
        /// </summary>
        public static string 連絡人名稱 {
            get {
                return ResourceManager.GetString("連絡人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連絡人地址 的當地語系化字串。
        /// </summary>
        public static string 連絡人地址 {
            get {
                return ResourceManager.GetString("連絡人地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立人統編 的當地語系化字串。
        /// </summary>
        public static string 開立人統編 {
            get {
                return ResourceManager.GetString("開立人統編", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立折讓證明 的當地語系化字串。
        /// </summary>
        public static string 開立折讓證明 {
            get {
                return ResourceManager.GetString("開立折讓證明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附件檔名 的當地語系化字串。
        /// </summary>
        public static string 附件檔名 {
            get {
                return ResourceManager.GetString("附件檔名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附件檔頁數 的當地語系化字串。
        /// </summary>
        public static string 附件檔頁數 {
            get {
                return ResourceManager.GetString("附件檔頁數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        public static string 電話 {
            get {
                return ResourceManager.GetString("電話", resourceCulture);
            }
        }
    }
}
