//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Controllers {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceQuery() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Controllers.InvoiceQuery", typeof(InvoiceQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 下載資料請求已送出!! 的當地語系化字串。
        /// </summary>
        public static string 下載資料請求已送出__ {
            get {
                return ResourceManager.GetString("下載資料請求已送出!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已作廢總筆數 的當地語系化字串。
        /// </summary>
        public static string 已作廢總筆數 {
            get {
                return ResourceManager.GetString("已作廢總筆數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已作廢總金額 的當地語系化字串。
        /// </summary>
        public static string 已作廢總金額 {
            get {
                return ResourceManager.GetString("已作廢總金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期 的當地語系化字串。
        /// </summary>
        public static string 日期 {
            get {
                return ResourceManager.GetString("日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未作廢總筆數 的當地語系化字串。
        /// </summary>
        public static string 未作廢總筆數 {
            get {
                return ResourceManager.GetString("未作廢總筆數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未作廢總金額 的當地語系化字串。
        /// </summary>
        public static string 未作廢總金額 {
            get {
                return ResourceManager.GetString("未作廢總金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無資料!! 的當地語系化字串。
        /// </summary>
        public static string 查無資料__ {
            get {
                return ResourceManager.GetString("查無資料!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票附件 的當地語系化字串。
        /// </summary>
        public static string 發票附件 {
            get {
                return ResourceManager.GetString("發票附件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總計 的當地語系化字串。
        /// </summary>
        public static string 總計 {
            get {
                return ResourceManager.GetString("總計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入9位數稅籍編號!! 的當地語系化字串。
        /// </summary>
        public static string 請輸入9位數稅籍編號__ {
            get {
                return ResourceManager.GetString("請輸入9位數稅籍編號!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇年度!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇年度__ {
            get {
                return ResourceManager.GetString("請選擇年度!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇期別!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇期別__ {
            get {
                return ResourceManager.GetString("請選擇期別!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇發票開立人!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇發票開立人__ {
            get {
                return ResourceManager.GetString("請選擇發票開立人!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇開立人!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇開立人__ {
            get {
                return ResourceManager.GetString("請選擇開立人!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料不存在!! 的當地語系化字串。
        /// </summary>
        public static string 資料不存在__ {
            get {
                return ResourceManager.GetString("資料不存在!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立發票月報表 的當地語系化字串。
        /// </summary>
        public static string 開立發票月報表 {
            get {
                return ResourceManager.GetString("開立發票月報表", resourceCulture);
            }
        }
    }
}
