//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Controllers {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceNo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceNo() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Controllers.InvoiceNo", typeof(InvoiceNo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 不符號碼大小順序與差距為50之倍數原則!! 的當地語系化字串。
        /// </summary>
        public static string 不符號碼大小順序與差距為50之倍數原則__ {
            get {
                return ResourceManager.GetString("不符號碼大小順序與差距為50之倍數原則!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 剩餘號碼不足單一本組數_無法分割_ 的當地語系化字串。
        /// </summary>
        public static string 剩餘號碼不足單一本組數_無法分割_ {
            get {
                return ResourceManager.GetString("剩餘號碼不足單一本組數_無法分割_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 整理完成!! 的當地語系化字串。
        /// </summary>
        public static string 整理完成__ {
            get {
                return ResourceManager.GetString("整理完成!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未設定字軌!! 的當地語系化字串。
        /// </summary>
        public static string 未設定字軌__ {
            get {
                return ResourceManager.GetString("未設定字軌!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人統編錯誤!! 的當地語系化字串。
        /// </summary>
        public static string 營業人統編錯誤__ {
            get {
                return ResourceManager.GetString("營業人統編錯誤!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 空白發票 的當地語系化字串。
        /// </summary>
        public static string 空白發票 {
            get {
                return ResourceManager.GetString("空白發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 空白發票字軌 的當地語系化字串。
        /// </summary>
        public static string 空白發票字軌 {
            get {
                return ResourceManager.GetString("空白發票字軌", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統中已存在重疊的區段!! 的當地語系化字串。
        /// </summary>
        public static string 系統中已存在重疊的區段__ {
            get {
                return ResourceManager.GetString("系統中已存在重疊的區段!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該區間之號碼已經被使用,不可修改!!!! 的當地語系化字串。
        /// </summary>
        public static string 該區間之號碼已經被使用_不可修改____ {
            get {
                return ResourceManager.GetString("該區間之號碼已經被使用,不可修改!!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入均分本數!! 的當地語系化字串。
        /// </summary>
        public static string 請輸入均分本數__ {
            get {
                return ResourceManager.GetString("請輸入均分本數!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇年份!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇年份__ {
            get {
                return ResourceManager.GetString("請選擇年份!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇期別!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇期別__ {
            get {
                return ResourceManager.GetString("請選擇期別!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇開立人!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇開立人__ {
            get {
                return ResourceManager.GetString("請選擇開立人!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料不存在!! 的當地語系化字串。
        /// </summary>
        public static string 資料不存在__ {
            get {
                return ResourceManager.GetString("資料不存在!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起號非8位整數!! 的當地語系化字串。
        /// </summary>
        public static string 起號非8位整數__ {
            get {
                return ResourceManager.GetString("起號非8位整數!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 迄號非8位整數!! 的當地語系化字串。
        /// </summary>
        public static string 迄號非8位整數__ {
            get {
                return ResourceManager.GetString("迄號非8位整數!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 違反序時序號原則該區段無法修改!! 的當地語系化字串。
        /// </summary>
        public static string 違反序時序號原則該區段無法修改__ {
            get {
                return ResourceManager.GetString("違反序時序號原則該區段無法修改!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 違反序時序號原則該區段無法新增!! 的當地語系化字串。
        /// </summary>
        public static string 違反序時序號原則該區段無法新增__ {
            get {
                return ResourceManager.GetString("違反序時序號原則該區段無法新增!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 配號區間資料錯誤!! 的當地語系化字串。
        /// </summary>
        public static string 配號區間資料錯誤__ {
            get {
                return ResourceManager.GetString("配號區間資料錯誤!!", resourceCulture);
            }
        }
    }
}
