//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Controllers {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserProfile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfile() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Controllers.UserProfile", typeof(UserProfile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 二組密碼輸入不同!! 的當地語系化字串。
        /// </summary>
        public static string 二組密碼輸入不同 {
            get {
                return ResourceManager.GetString("二組密碼輸入不同", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不可少於６個字碼!! 的當地語系化字串。
        /// </summary>
        public static string 密碼不可少於６個字碼 {
            get {
                return ResourceManager.GetString("密碼不可少於６個字碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不可為空白!! 的當地語系化字串。
        /// </summary>
        public static string 密碼不可為空白 {
            get {
                return ResourceManager.GetString("密碼不可為空白", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼須由英文、數字組成!! 的當地語系化字串。
        /// </summary>
        public static string 密碼須由英文_數字組成 {
            get {
                return ResourceManager.GetString("密碼須由英文_數字組成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號不可為空白!! 的當地語系化字串。
        /// </summary>
        public static string 帳號不可為空白 {
            get {
                return ResourceManager.GetString("帳號不可為空白", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇所屬會員!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇所屬會員 {
            get {
                return ResourceManager.GetString("請選擇所屬會員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇身份設定!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇身份設定 {
            get {
                return ResourceManager.GetString("請選擇身份設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料已修改!! 的當地語系化字串。
        /// </summary>
        public static string 資料已修改 {
            get {
                return ResourceManager.GetString("資料已修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料錯誤!! 的當地語系化字串。
        /// </summary>
        public static string 資料錯誤 {
            get {
                return ResourceManager.GetString("資料錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 這個帳號已被使用，請更換申請帳號!! 的當地語系化字串。
        /// </summary>
        public static string 這個帳號已被使用_更換申請帳號 {
            get {
                return ResourceManager.GetString("這個帳號已被使用_更換申請帳號", resourceCulture);
            }
        }
    }
}
