//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.DataExchange.Module {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataIndex() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.DataExchange.Module.DataIndex", typeof(DataIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 下載範本 的當地語系化字串。
        /// </summary>
        public static string 下載範本 {
            get {
                return ResourceManager.GetString("下載範本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳送更新 的當地語系化字串。
        /// </summary>
        public static string 傳送更新 {
            get {
                return ResourceManager.GetString("傳送更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 各項資料 的當地語系化字串。
        /// </summary>
        public static string 各項資料 {
            get {
                return ResourceManager.GetString("各項資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票字軌 的當地語系化字串。
        /// </summary>
        public static string 發票字軌 {
            get {
                return ResourceManager.GetString("發票字軌", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票資料 的當地語系化字串。
        /// </summary>
        public static string 發票資料 {
            get {
                return ResourceManager.GetString("發票資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 立即傳送 的當地語系化字串。
        /// </summary>
        public static string 立即傳送 {
            get {
                return ResourceManager.GetString("立即傳送", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇檔案!! 的當地語系化字串。
        /// </summary>
        public static string 請選擇檔案__ {
            get {
                return ResourceManager.GetString("請選擇檔案!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人 的當地語系化字串。
        /// </summary>
        public static string 買受人 {
            get {
                return ResourceManager.GetString("買受人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料修改 的當地語系化字串。
        /// </summary>
        public static string 資料修改 {
            get {
                return ResourceManager.GetString("資料修改", resourceCulture);
            }
        }
    }
}
