//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProcessMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationResource.ProcessMessage", typeof(ProcessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel格式發票開立請求檔.
        /// </summary>
        public static string P101 {
            get {
                return ResourceManager.GetString("P101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel格式作廢發票請求檔.
        /// </summary>
        public static string P102 {
            get {
                return ResourceManager.GetString("P102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel格式開立折讓單請求檔.
        /// </summary>
        public static string P103 {
            get {
                return ResourceManager.GetString("P103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel格式作廢折讓單請求檔.
        /// </summary>
        public static string P104 {
            get {
                return ResourceManager.GetString("P104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel格式開立發票完全折讓請求檔.
        /// </summary>
        public static string P113 {
            get {
                return ResourceManager.GetString("P113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json格式作廢發票請求檔.
        /// </summary>
        public static string P202 {
            get {
                return ResourceManager.GetString("P202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json格式開立折讓單請求檔.
        /// </summary>
        public static string P203 {
            get {
                return ResourceManager.GetString("P203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json格式作廢折讓單請求檔.
        /// </summary>
        public static string P204 {
            get {
                return ResourceManager.GetString("P204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml格式發票開立請求檔(境外電商).
        /// </summary>
        public static string P501 {
            get {
                return ResourceManager.GetString("P501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json格式發票開立請求檔(境外電商).
        /// </summary>
        public static string P601 {
            get {
                return ResourceManager.GetString("P601", resourceCulture);
            }
        }
    }
}
