//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.Organization.Module {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemForm() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.Organization.Module.ItemForm", typeof(ItemForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 B2B發票買受人可重複列印 的當地語系化字串。
        /// </summary>
        public static string B2B發票買受人可重複列印 {
            get {
                return ResourceManager.GetString("B2B發票買受人可重複列印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 B2B發票開立通知以鏈結取代附件 的當地語系化字串。
        /// </summary>
        public static string B2B發票開立通知以鏈結取代附件 {
            get {
                return ResourceManager.GetString("B2B發票開立通知以鏈結取代附件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一般稅額計算之電子發票 的當地語系化字串。
        /// </summary>
        public static string 一般稅額計算之電子發票 {
            get {
                return ResourceManager.GetString("一般稅額計算之電子發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上期發票空白號碼 的當地語系化字串。
        /// </summary>
        public static string 上期發票空白號碼 {
            get {
                return ResourceManager.GetString("上期發票空白號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 作廢折讓 的當地語系化字串。
        /// </summary>
        public static string 作廢折讓 {
            get {
                return ResourceManager.GetString("作廢折讓", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 作廢發票 的當地語系化字串。
        /// </summary>
        public static string 作廢發票 {
            get {
                return ResourceManager.GetString("作廢發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用傳送企業發票對應資料 的當地語系化字串。
        /// </summary>
        public static string 使用傳送企業發票對應資料 {
            get {
                return ResourceManager.GetString("使用傳送企業發票對應資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用境外電商郵件樣式 的當地語系化字串。
        /// </summary>
        public static string 使用境外電商郵件樣式 {
            get {
                return ResourceManager.GetString("使用境外電商郵件樣式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用委外客服 的當地語系化字串。
        /// </summary>
        public static string 使用委外客服 {
            get {
                return ResourceManager.GetString("使用委外客服", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用客訂郵件樣式 的當地語系化字串。
        /// </summary>
        public static string 使用客訂郵件樣式 {
            get {
                return ResourceManager.GetString("使用客訂郵件樣式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用簡訊通知買受人 的當地語系化字串。
        /// </summary>
        public static string 使用簡訊通知買受人 {
            get {
                return ResourceManager.GetString("使用簡訊通知買受人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳真 的當地語系化字串。
        /// </summary>
        public static string 傳真 {
            get {
                return ResourceManager.GetString("傳真", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司統一編號 的當地語系化字串。
        /// </summary>
        public static string 公司統一編號 {
            get {
                return ResourceManager.GetString("公司統一編號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司識別標章 的當地語系化字串。
        /// </summary>
        public static string 公司識別標章 {
            get {
                return ResourceManager.GetString("公司識別標章", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司負責人 的當地語系化字串。
        /// </summary>
        public static string 公司負責人 {
            get {
                return ResourceManager.GetString("公司負責人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        public static string 名稱 {
            get {
                return ResourceManager.GetString("名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地址 的當地語系化字串。
        /// </summary>
        public static string 地址 {
            get {
                return ResourceManager.GetString("地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 基本資料 的當地語系化字串。
        /// </summary>
        public static string 基本資料 {
            get {
                return ResourceManager.GetString("基本資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客服專用電子郵件 的當地語系化字串。
        /// </summary>
        public static string 客服專用電子郵件 {
            get {
                return ResourceManager.GetString("客服專用電子郵件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客服專線 的當地語系化字串。
        /// </summary>
        public static string 客服專線 {
            get {
                return ResourceManager.GetString("客服專線", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客訂樣式 的當地語系化字串。
        /// </summary>
        public static string 客訂樣式 {
            get {
                return ResourceManager.GetString("客訂樣式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄送中獎通知 的當地語系化字串。
        /// </summary>
        public static string 寄送中獎通知 {
            get {
                return ResourceManager.GetString("寄送中獎通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄送作廢折讓通知 的當地語系化字串。
        /// </summary>
        public static string 寄送作廢折讓通知 {
            get {
                return ResourceManager.GetString("寄送作廢折讓通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄送作廢通知 的當地語系化字串。
        /// </summary>
        public static string 寄送作廢通知 {
            get {
                return ResourceManager.GetString("寄送作廢通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄送折讓通知 的當地語系化字串。
        /// </summary>
        public static string 寄送折讓通知 {
            get {
                return ResourceManager.GetString("寄送折讓通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄送開立通知 的當地語系化字串。
        /// </summary>
        public static string 寄送開立通知 {
            get {
                return ResourceManager.GetString("寄送開立通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 折讓單列印樣式 的當地語系化字串。
        /// </summary>
        public static string 折讓單列印樣式 {
            get {
                return ResourceManager.GetString("折讓單列印樣式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        public static string 是 {
            get {
                return ResourceManager.GetString("是", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人 的當地語系化字串。
        /// </summary>
        public static string 營業人 {
            get {
                return ResourceManager.GetString("營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 特種稅額計算之電子發票 的當地語系化字串。
        /// </summary>
        public static string 特種稅額計算之電子發票 {
            get {
                return ResourceManager.GetString("特種稅額計算之電子發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 用戶端自動下載 的當地語系化字串。
        /// </summary>
        public static string 用戶端自動下載 {
            get {
                return ResourceManager.GetString("用戶端自動下載", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票列印樣式 的當地語系化字串。
        /// </summary>
        public static string 發票列印樣式 {
            get {
                return ResourceManager.GetString("發票列印樣式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票折讓 的當地語系化字串。
        /// </summary>
        public static string 發票折讓 {
            get {
                return ResourceManager.GetString("發票折讓", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票開立 的當地語系化字串。
        /// </summary>
        public static string 發票開立 {
            get {
                return ResourceManager.GetString("發票開立", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簡訊通知 的當地語系化字串。
        /// </summary>
        public static string 簡訊通知 {
            get {
                return ResourceManager.GetString("簡訊通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人姓名 的當地語系化字串。
        /// </summary>
        public static string 聯絡人姓名 {
            get {
                return ResourceManager.GetString("聯絡人姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人職稱 的當地語系化字串。
        /// </summary>
        public static string 聯絡人職稱 {
            get {
                return ResourceManager.GetString("聯絡人職稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人行動電話 的當地語系化字串。
        /// </summary>
        public static string 聯絡人行動電話 {
            get {
                return ResourceManager.GetString("聯絡人行動電話", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人電子郵件 的當地語系化字串。
        /// </summary>
        public static string 聯絡人電子郵件 {
            get {
                return ResourceManager.GetString("聯絡人電子郵件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人電話 的當地語系化字串。
        /// </summary>
        public static string 聯絡人電話 {
            get {
                return ResourceManager.GetString("聯絡人電話", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡方式 的當地語系化字串。
        /// </summary>
        public static string 聯絡方式 {
            get {
                return ResourceManager.GetString("聯絡方式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自動核准列印 的當地語系化字串。
        /// </summary>
        public static string 自動核准列印 {
            get {
                return ResourceManager.GetString("自動核准列印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息通知 的當地語系化字串。
        /// </summary>
        public static string 訊息通知 {
            get {
                return ResourceManager.GetString("訊息通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定使用委外客服 的當地語系化字串。
        /// </summary>
        public static string 設定使用委外客服 {
            get {
                return ResourceManager.GetString("設定使用委外客服", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定使用發票列印 的當地語系化字串。
        /// </summary>
        public static string 設定使用發票列印 {
            get {
                return ResourceManager.GetString("設定使用發票列印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定傳送發票對應資料 的當地語系化字串。
        /// </summary>
        public static string 設定傳送發票對應資料 {
            get {
                return ResourceManager.GetString("設定傳送發票對應資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定接收B2B發票(PDF檔) 的當地語系化字串。
        /// </summary>
        public static string 設定接收B2B發票_PDF檔_ {
            get {
                return ResourceManager.GetString("設定接收B2B發票(PDF檔)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定發票資料全列印 的當地語系化字串。
        /// </summary>
        public static string 設定發票資料全列印 {
            get {
                return ResourceManager.GetString("設定發票資料全列印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定發票類別 的當地語系化字串。
        /// </summary>
        public static string 設定發票類別 {
            get {
                return ResourceManager.GetString("設定發票類別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定項目 的當地語系化字串。
        /// </summary>
        public static string 設定項目 {
            get {
                return ResourceManager.GetString("設定項目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇 的當地語系化字串。
        /// </summary>
        public static string 請選擇 {
            get {
                return ResourceManager.GetString("請選擇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立發票字軌號碼檢核 的當地語系化字串。
        /// </summary>
        public static string 開立發票字軌號碼檢核 {
            get {
                return ResourceManager.GetString("開立發票字軌號碼檢核", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子發票核准函號 的當地語系化字串。
        /// </summary>
        public static string 電子發票核准函號 {
            get {
                return ResourceManager.GetString("電子發票核准函號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        public static string 電話 {
            get {
                return ResourceManager.GetString("電話", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 類別 的當地語系化字串。
        /// </summary>
        public static string 類別 {
            get {
                return ResourceManager.GetString("類別", resourceCulture);
            }
        }
    }
}
