//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.Handling.MailTracking {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailTrackingMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailTrackingMessage() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.Handling.MailTracking.MailTrackingMessage", typeof(MailTrackingMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 全部 的當地語系化字串。
        /// </summary>
        public static string 全部 {
            get {
                return ResourceManager.GetString("全部", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 初次寄送 的當地語系化字串。
        /// </summary>
        public static string 初次寄送 {
            get {
                return ResourceManager.GetString("初次寄送", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄件日期 的當地語系化字串。
        /// </summary>
        public static string 寄件日期 {
            get {
                return ResourceManager.GetString("寄件日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄件過程 的當地語系化字串。
        /// </summary>
        public static string 寄件過程 {
            get {
                return ResourceManager.GetString("寄件過程", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有 的當地語系化字串。
        /// </summary>
        public static string 有 {
            get {
                return ResourceManager.GetString("有", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string 查詢 {
            get {
                return ResourceManager.GetString("查詢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清除 的當地語系化字串。
        /// </summary>
        public static string 清除 {
            get {
                return ResourceManager.GetString("清除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無 的當地語系化字串。
        /// </summary>
        public static string 無 {
            get {
                return ResourceManager.GetString("無", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登錄掛號郵件 的當地語系化字串。
        /// </summary>
        public static string 登錄掛號郵件 {
            get {
                return ResourceManager.GetString("登錄掛號郵件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票號碼(起號) 的當地語系化字串。
        /// </summary>
        public static string 發票號碼_起號_ {
            get {
                return ResourceManager.GetString("發票號碼(起號)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票號碼(迄號) 的當地語系化字串。
        /// </summary>
        public static string 發票號碼_迄號_ {
            get {
                return ResourceManager.GetString("發票號碼(迄號)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 退回重寄 的當地語系化字串。
        /// </summary>
        public static string 退回重寄 {
            get {
                return ResourceManager.GetString("退回重寄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件張數 的當地語系化字串。
        /// </summary>
        public static string 郵件張數 {
            get {
                return ResourceManager.GetString("郵件張數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件號碼1(流水號碼段) 的當地語系化字串。
        /// </summary>
        public static string 郵件號碼1_流水號碼段_ {
            get {
                return ResourceManager.GetString("郵件號碼1(流水號碼段)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件號碼2(固定號碼段) 的當地語系化字串。
        /// </summary>
        public static string 郵件號碼2_固定號碼段_ {
            get {
                return ResourceManager.GetString("郵件號碼2(固定號碼段)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附件檔 的當地語系化字串。
        /// </summary>
        public static string 附件檔 {
            get {
                return ResourceManager.GetString("附件檔", resourceCulture);
            }
        }
    }
}
