//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.Handling.MailTracking {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TableList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TableList() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.Handling.MailTracking.TableList", typeof(TableList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 的當地語系化字串。
        /// </summary>
        public static string 下載 {
            get {
                return ResourceManager.GetString("下載", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 作業方式 的當地語系化字串。
        /// </summary>
        public static string 作業方式 {
            get {
                return ResourceManager.GetString("作業方式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備考 的當地語系化字串。
        /// </summary>
        public static string 備考 {
            get {
                return ResourceManager.GetString("備考", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印資料下載(ZIP) 的當地語系化字串。
        /// </summary>
        public static string 列印資料下載_ZIP_ {
            get {
                return ResourceManager.GetString("列印資料下載(ZIP)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 存檔 的當地語系化字串。
        /// </summary>
        public static string 存檔 {
            get {
                return ResourceManager.GetString("存檔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寄送日期 的當地語系化字串。
        /// </summary>
        public static string 寄送日期 {
            get {
                return ResourceManager.GetString("寄送日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 掛號號碼 的當地語系化字串。
        /// </summary>
        public static string 掛號號碼 {
            get {
                return ResourceManager.GetString("掛號號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收件人 的當地語系化字串。
        /// </summary>
        public static string 收件人 {
            get {
                return ResourceManager.GetString("收件人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收件人地址 的當地語系化字串。
        /// </summary>
        public static string 收件人地址 {
            get {
                return ResourceManager.GetString("收件人地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 整理郵件號碼 的當地語系化字串。
        /// </summary>
        public static string 整理郵件號碼 {
            get {
                return ResourceManager.GetString("整理郵件號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票號碼 的當地語系化字串。
        /// </summary>
        public static string 發票號碼 {
            get {
                return ResourceManager.GetString("發票號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附件張數 的當地語系化字串。
        /// </summary>
        public static string 附件張數 {
            get {
                return ResourceManager.GetString("附件張數", resourceCulture);
            }
        }
    }
}
