//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.Forms {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class B2BInvoice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal B2BInvoice() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.Forms.B2BInvoice", typeof(B2BInvoice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 一般稅額計算之電子發票 的當地語系化字串。
        /// </summary>
        public static string 一般稅額計算之電子發票 {
            get {
                return ResourceManager.GetString("一般稅額計算之電子發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不得抵扣之固定資產 的當地語系化字串。
        /// </summary>
        public static string 不得抵扣之固定資產 {
            get {
                return ResourceManager.GetString("不得抵扣之固定資產", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不得抵扣之進貨及費用 的當地語系化字串。
        /// </summary>
        public static string 不得抵扣之進貨及費用 {
            get {
                return ResourceManager.GetString("不得抵扣之進貨及費用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string 備註 {
            get {
                return ResourceManager.GetString("備註", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 免稅 的當地語系化字串。
        /// </summary>
        public static string 免稅 {
            get {
                return ResourceManager.GetString("免稅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string 刪除 {
            get {
                return ResourceManager.GetString("刪除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 含稅 的當地語系化字串。
        /// </summary>
        public static string 含稅 {
            get {
                return ResourceManager.GetString("含稅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品名 的當地語系化字串。
        /// </summary>
        public static string 品名 {
            get {
                return ResourceManager.GetString("品名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單價 的當地語系化字串。
        /// </summary>
        public static string 單價 {
            get {
                return ResourceManager.GetString("單價", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 小計 的當地語系化字串。
        /// </summary>
        public static string 小計 {
            get {
                return ResourceManager.GetString("小計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 得抵扣之固定資產 的當地語系化字串。
        /// </summary>
        public static string 得抵扣之固定資產 {
            get {
                return ResourceManager.GetString("得抵扣之固定資產", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 得抵扣之進貨及費用 的當地語系化字串。
        /// </summary>
        public static string 得抵扣之進貨及費用 {
            get {
                return ResourceManager.GetString("得抵扣之進貨及費用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應稅 的當地語系化字串。
        /// </summary>
        public static string 應稅 {
            get {
                return ResourceManager.GetString("應稅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數量 的當地語系化字串。
        /// </summary>
        public static string 數量 {
            get {
                return ResourceManager.GetString("數量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新台幣 的當地語系化字串。
        /// </summary>
        public static string 新台幣 {
            get {
                return ResourceManager.GetString("新台幣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增發票主檔 的當地語系化字串。
        /// </summary>
        public static string 新增發票主檔 {
            get {
                return ResourceManager.GetString("新增發票主檔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未稅 的當地語系化字串。
        /// </summary>
        public static string 未稅 {
            get {
                return ResourceManager.GetString("未稅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沖帳別 的當地語系化字串。
        /// </summary>
        public static string 沖帳別 {
            get {
                return ResourceManager.GetString("沖帳別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清除 的當地語系化字串。
        /// </summary>
        public static string 清除 {
            get {
                return ResourceManager.GetString("清除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人 的當地語系化字串。
        /// </summary>
        public static string 營業人 {
            get {
                return ResourceManager.GetString("營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業稅額 的當地語系化字串。
        /// </summary>
        public static string 營業稅額 {
            get {
                return ResourceManager.GetString("營業稅額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 特種稅率 的當地語系化字串。
        /// </summary>
        public static string 特種稅率 {
            get {
                return ResourceManager.GetString("特種稅率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 特種稅額計算之電子發票 的當地語系化字串。
        /// </summary>
        public static string 特種稅額計算之電子發票 {
            get {
                return ResourceManager.GetString("特種稅額計算之電子發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品編號 的當地語系化字串。
        /// </summary>
        public static string 產品編號 {
            get {
                return ResourceManager.GetString("產品編號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票 的當地語系化字串。
        /// </summary>
        public static string 發票 {
            get {
                return ResourceManager.GetString("發票", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票明細 的當地語系化字串。
        /// </summary>
        public static string 發票明細 {
            get {
                return ResourceManager.GetString("發票明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票檢查碼 的當地語系化字串。
        /// </summary>
        public static string 發票檢查碼 {
            get {
                return ResourceManager.GetString("發票檢查碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票開立 的當地語系化字串。
        /// </summary>
        public static string 發票開立 {
            get {
                return ResourceManager.GetString("發票開立", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票開立人 的當地語系化字串。
        /// </summary>
        public static string 發票開立人 {
            get {
                return ResourceManager.GetString("發票開立人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票預覽 的當地語系化字串。
        /// </summary>
        public static string 發票預覽 {
            get {
                return ResourceManager.GetString("發票預覽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票類別 的當地語系化字串。
        /// </summary>
        public static string 發票類別 {
            get {
                return ResourceManager.GetString("發票類別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相關號碼 的當地語系化字串。
        /// </summary>
        public static string 相關號碼 {
            get {
                return ResourceManager.GetString("相關號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定刪除此項資料? 的當地語系化字串。
        /// </summary>
        public static string 確定刪除此項資料_ {
            get {
                return ResourceManager.GetString("確定刪除此項資料?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 稅率 的當地語系化字串。
        /// </summary>
        public static string 稅率 {
            get {
                return ResourceManager.GetString("稅率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 經海關出口 的當地語系化字串。
        /// </summary>
        public static string 經海關出口 {
            get {
                return ResourceManager.GetString("經海關出口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總備註 的當地語系化字串。
        /// </summary>
        public static string 總備註 {
            get {
                return ResourceManager.GetString("總備註", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總計 的當地語系化字串。
        /// </summary>
        public static string 總計 {
            get {
                return ResourceManager.GetString("總計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 若為零稅率發票，此為必填欄位 的當地語系化字串。
        /// </summary>
        public static string 若為零稅率發票_此為必填欄位 {
            get {
                return ResourceManager.GetString("若為零稅率發票_此為必填欄位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設為相對營業人 的當地語系化字串。
        /// </summary>
        public static string 設為相對營業人 {
            get {
                return ResourceManager.GetString("設為相對營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 課稅別 的當地語系化字串。
        /// </summary>
        public static string 課稅別 {
            get {
                return ResourceManager.GetString("課稅別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人email 的當地語系化字串。
        /// </summary>
        public static string 買受人email {
            get {
                return ResourceManager.GetString("買受人email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人名稱 的當地語系化字串。
        /// </summary>
        public static string 買受人名稱 {
            get {
                return ResourceManager.GetString("買受人名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人地址 的當地語系化字串。
        /// </summary>
        public static string 買受人地址 {
            get {
                return ResourceManager.GetString("買受人地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人為新客戶，是否設為相對營業人？ 的當地語系化字串。
        /// </summary>
        public static string 買受人為新客戶_是否設為相對營業人_ {
            get {
                return ResourceManager.GetString("買受人為新客戶_是否設為相對營業人_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人統編 的當地語系化字串。
        /// </summary>
        public static string 買受人統編 {
            get {
                return ResourceManager.GetString("買受人統編", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人註記 的當地語系化字串。
        /// </summary>
        public static string 買受人註記 {
            get {
                return ResourceManager.GetString("買受人註記", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人電話 的當地語系化字串。
        /// </summary>
        public static string 買受人電話 {
            get {
                return ResourceManager.GetString("買受人電話", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通關方式註記 的當地語系化字串。
        /// </summary>
        public static string 通關方式註記 {
            get {
                return ResourceManager.GetString("通關方式註記", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售品項稅額 的當地語系化字串。
        /// </summary>
        public static string 銷售品項稅額 {
            get {
                return ResourceManager.GetString("銷售品項稅額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷售額合計 的當地語系化字串。
        /// </summary>
        public static string 銷售額合計 {
            get {
                return ResourceManager.GetString("銷售額合計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關閉 的當地語系化字串。
        /// </summary>
        public static string 關閉 {
            get {
                return ResourceManager.GetString("關閉", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 零稅率 的當地語系化字串。
        /// </summary>
        public static string 零稅率 {
            get {
                return ResourceManager.GetString("零稅率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子發票開立 的當地語系化字串。
        /// </summary>
        public static string 電子發票開立 {
            get {
                return ResourceManager.GetString("電子發票開立", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非經海關出口 的當地語系化字串。
        /// </summary>
        public static string 非經海關出口 {
            get {
                return ResourceManager.GetString("非經海關出口", resourceCulture);
            }
        }
    }
}
