//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.Forms {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SimpleInvoice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimpleInvoice() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.Forms.SimpleInvoice", typeof(SimpleInvoice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 不使用 的當地語系化字串。
        /// </summary>
        public static string 不使用 {
            get {
                return ResourceManager.GetString("不使用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分店號碼 的當地語系化字串。
        /// </summary>
        public static string 分店號碼 {
            get {
                return ResourceManager.GetString("分店號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 愛心碼 的當地語系化字串。
        /// </summary>
        public static string 愛心碼 {
            get {
                return ResourceManager.GetString("愛心碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手機條碼 的當地語系化字串。
        /// </summary>
        public static string 手機條碼 {
            get {
                return ResourceManager.GetString("手機條碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無 的當地語系化字串。
        /// </summary>
        public static string 無 {
            get {
                return ResourceManager.GetString("無", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自然人憑證條碼 的當地語系化字串。
        /// </summary>
        public static string 自然人憑證條碼 {
            get {
                return ResourceManager.GetString("自然人憑證條碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人為保稅區(自由貿易港區) 的當地語系化字串。
        /// </summary>
        public static string 買受人為保稅區_自由貿易港區_ {
            get {
                return ResourceManager.GetString("買受人為保稅區(自由貿易港區)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人為園區事業 的當地語系化字串。
        /// </summary>
        public static string 買受人為園區事業 {
            get {
                return ResourceManager.GetString("買受人為園區事業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人為遠洋漁業 的當地語系化字串。
        /// </summary>
        public static string 買受人為遠洋漁業 {
            get {
                return ResourceManager.GetString("買受人為遠洋漁業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人簽署適用零稅率註記 的當地語系化字串。
        /// </summary>
        public static string 買受人簽署適用零稅率註記 {
            get {
                return ResourceManager.GetString("買受人簽署適用零稅率註記", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載具號碼 的當地語系化字串。
        /// </summary>
        public static string 載具號碼 {
            get {
                return ResourceManager.GetString("載具號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載具類型 的當地語系化字串。
        /// </summary>
        public static string 載具類型 {
            get {
                return ResourceManager.GetString("載具類型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隨機碼 的當地語系化字串。
        /// </summary>
        public static string 隨機碼 {
            get {
                return ResourceManager.GetString("隨機碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 &gt; 電子發票開立 的當地語系化字串。
        /// </summary>
        public static string 首頁___電子發票開立 {
            get {
                return ResourceManager.GetString("首頁 > 電子發票開立", resourceCulture);
            }
        }
    }
}
