//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIVOGo.Resource.Views.Forms {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SimpleAllowance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimpleAllowance() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eIVOGo.Resource.Views.Forms.SimpleAllowance", typeof(SimpleAllowance).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 原品名 的當地語系化字串。
        /// </summary>
        public static string 原品名 {
            get {
                return ResourceManager.GetString("原品名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原發票日期 的當地語系化字串。
        /// </summary>
        public static string 原發票日期 {
            get {
                return ResourceManager.GetString("原發票日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原發票號碼 的當地語系化字串。
        /// </summary>
        public static string 原發票號碼 {
            get {
                return ResourceManager.GetString("原發票號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        public static string 單位 {
            get {
                return ResourceManager.GetString("單位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單價 的當地語系化字串。
        /// </summary>
        public static string 單價 {
            get {
                return ResourceManager.GetString("單價", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 小計 的當地語系化字串。
        /// </summary>
        public static string 小計 {
            get {
                return ResourceManager.GetString("小計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 折讓明細 的當地語系化字串。
        /// </summary>
        public static string 折讓明細 {
            get {
                return ResourceManager.GetString("折讓明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數量 的當地語系化字串。
        /// </summary>
        public static string 數量 {
            get {
                return ResourceManager.GetString("數量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未稅金額 的當地語系化字串。
        /// </summary>
        public static string 未稅金額 {
            get {
                return ResourceManager.GetString("未稅金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未稅金額總計 的當地語系化字串。
        /// </summary>
        public static string 未稅金額總計 {
            get {
                return ResourceManager.GetString("未稅金額總計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清除 的當地語系化字串。
        /// </summary>
        public static string 清除 {
            get {
                return ResourceManager.GetString("清除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業人 的當地語系化字串。
        /// </summary>
        public static string 營業人 {
            get {
                return ResourceManager.GetString("營業人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業稅額 的當地語系化字串。
        /// </summary>
        public static string 營業稅額 {
            get {
                return ResourceManager.GetString("營業稅額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營業稅額合計 的當地語系化字串。
        /// </summary>
        public static string 營業稅額合計 {
            get {
                return ResourceManager.GetString("營業稅額合計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票開立人 的當地語系化字串。
        /// </summary>
        public static string 發票開立人 {
            get {
                return ResourceManager.GetString("發票開立人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貨品單價含稅 的當地語系化字串。
        /// </summary>
        public static string 貨品單價含稅 {
            get {
                return ResourceManager.GetString("貨品單價含稅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 買受人 的當地語系化字串。
        /// </summary>
        public static string 買受人 {
            get {
                return ResourceManager.GetString("買受人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立 的當地語系化字串。
        /// </summary>
        public static string 開立 {
            get {
                return ResourceManager.GetString("開立", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開立折讓證明單 的當地語系化字串。
        /// </summary>
        public static string 開立折讓證明單 {
            get {
                return ResourceManager.GetString("開立折讓證明單", resourceCulture);
            }
        }
    }
}
